[pytest]

testpaths = tests

python_files = test_*.py *_test.py *.spec.py

pythonpath = .

addopts =
    -v
    --import-mode=importlib
    --alluredir=allure-results

markers =
    ui
    api
    security
    performance
    accessibility
    ai