apiVersion: apps/v1
kind: Deployment

metadata:
  name: qa_sdet
  namespace: qa_sdet

spec:
  replicas: 1

  selector:
    matchLabels:
      app: qa_sdet

  template:
    metadata:
      labels:
        app: qa_sdet

    spec:
      containers:
        - name: qa_sdet
          image: qa_sdet:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: qa_sdet-config