# Kafka 4.0 (KRaft mode)
image:
  registry: docker.io
  repository: bitnamilegacy/kafka
  tag: 4.0.0-debian-12-r10

kraft:
  enabled: true

zookeeper:
  enabled: false

controller:
  replicaCount: 1

broker:
  replicaCount: 1

listeners:
  client:
    protocol: PLAINTEXT

externalAccess:
  enabled: false

persistence:
  enabled: true
  size: 8Gi

resources:
  requests:
    cpu: 500m
    memory: 512Mi

  limits:
    cpu: 1000m
    memory: 1Gi